<?php

namespace AppBundle\Repository;

/**
 * BoletinSalidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoletinSalidaRepository extends \Doctrine\ORM\EntityRepository
{
}
